name: rubocop
adopt-info: rubocop
base: core22
grade: stable
confinement: strict
architectures:
  - build-on: [amd64]
  - build-on: [arm64]
parts:
  rubocop:
    source: https://github.com/rubocop/rubocop
    source-type: git
    plugin: nil
    override-build: |
      sed -i 's|!solaris_platform|win_platform|' $SNAPCRAFT_PART_INSTALL/usr/lib/ruby/vendor_ruby/rubygems.rb
      # Build and install
      /usr/bin/gem build *.gemspec
      /usr/bin/gem install *.gem --env-shebang --no-document

      # Set the version
      version="$(rubocop -v)"
      craftctl set version="$version"

      # Move files
      mkdir -p "$SNAPCRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp -R /var/lib/gems/3.0.0/* "$CRAFT_PART_INSTALL/var/lib/gems/3.0.0/"
      cp /usr/local/bin/rubocop "$SNAPCRAFT_PART_INSTALL/usr/bin/"
    build-packages:
      - ruby3.0
      - gcc
      - libc6-dev
      - make
      - ruby3.0-dev
    stage-packages:
      - ruby3.0
      - rubygems
      - libruby3.0

apps:
  rubocop:
    environment: &appenv
      HOME: $SNAP_REAL_HOME
      # ruby env variables
      RUBYLIB: "${SNAP}/usr/lib/ruby/vendor_ruby/3.0.0:${SNAP}/usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/3.0.0:${SNAP}/usr/lib/ruby/vendor_ruby:${SNAP}/usr/lib/ruby/3.0.0:${SNAP}/usr/lib/x86_64-linux-gnu/ruby/3.0.0"
      GEM_HOME: "${SNAP}/var/lib/gems/3.0.0"
      GEM_PATH: "${SNAP}/usr/lib/ruby/gems/3.0.0:${SNAP}/usr/share/rubygems-integration/all:${SNAP}/var/lib/gems/3.0.0"
      RUBOCOP_CACHE_ROOT: "$SNAP_USER_DATA/.cache/rubocop_cache"
    command: usr/bin/ruby $SNAP/usr/bin/rubocop
    plugs:
      - home
title: Rubocop
summary: A Ruby linter and formatter
description: |
  Rubocop is a Ruby linter and formatter. It has a series of checks for aspects
  such as style, code metrics, and naming. Rubocop also verifies for security
  concerns: unsafe evaluation, YAML deserializations, and many more. The
  formatter capability can be used to fix many of the issues automatically.
icon: images/icon.png
issues:
  - https://github.com/canonical/rubocop-snap/issues
  - https://github.com/rubocop/rubocop
license: MIT
website: https://github.com/canonical/rubocop-snap
